"""pridanie profil_fotka_skupina do Skupina

Revision ID: 094c243357a2
Revises: 
Create Date: 2025-07-16 11:16:45.694501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094c243357a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skupina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_fotka_skupina', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skupina', schema=None) as batch_op:
        batch_op.drop_column('profil_fotka_skupina')

    # ### end Alembic commands ###
