"""video: add zanre (CSV)

Revision ID: 0cd5534fc533
Revises: add_stav_delete_at_to_podujatie
Create Date: 2025-10-11 13:15:06.002854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd5534fc533'
down_revision = 'add_stav_delete_at_to_podujatie'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_pouzivatel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zanre', sa.String(length=255), nullable=True))

    with op.batch_alter_table('video_skupina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zanre', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_skupina', schema=None) as batch_op:
        batch_op.drop_column('zanre')

    with op.batch_alter_table('video_pouzivatel', schema=None) as batch_op:
        batch_op.drop_column('zanre')

    # ### end Alembic commands ###
