"""dopyt: add aktivny + zmazany_at

Revision ID: 188b7f45e688
Revises: 2ab758816023
Create Date: 2025-08-19 12:56:12.696093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188b7f45e688'
down_revision = '2ab758816023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aktivny', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('zmazany_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.drop_column('zmazany_at')
        batch_op.drop_column('aktivny')

    # ### end Alembic commands ###
