"""dopyt: add aktivny + zmazany_at

Revision ID: 2ab758816023
Revises: eb7190782479
Create Date: 2025-08-19 12:55:06.116888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab758816023'
down_revision = 'eb7190782479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprava')
    with op.batch_alter_table('spravy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('komu_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('komu_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spravy', schema=None) as batch_op:
        batch_op.alter_column('komu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('komu_email')

    op.create_table('sprava',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('obsah', sa.TEXT(), nullable=False),
    sa.Column('datum', sa.DATETIME(), nullable=True),
    sa.Column('od_id', sa.INTEGER(), nullable=False),
    sa.Column('komu_id', sa.INTEGER(), nullable=False),
    sa.Column('inzerat_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['inzerat_id'], ['inzerat.id'], ),
    sa.ForeignKeyConstraint(['komu_id'], ['pouzivatel.id'], ),
    sa.ForeignKeyConstraint(['od_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
