"""Dopyt: add mesto_id FK to Mesto

Revision ID: 326c001caaa5
Revises: 77fe8d51e432
Create Date: 2025-08-18 10:39:27.583790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326c001caaa5'
down_revision = '77fe8d51e432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_dopyt_mesto', 'mesto', ['mesto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dopyt_mesto', type_='foreignkey')
        batch_op.drop_column('mesto_id')

    # ### end Alembic commands ###
