"""user erase extras (token, feedback, erased_at)

Revision ID: 5225307a69e8
Revises: 93c7beb658e0
Create Date: 2025-09-24 14:47:04.876306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5225307a69e8'
down_revision = '93c7beb658e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erase_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('erase_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('erased_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pouzivatel_erase_token'), ['erase_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pouzivatel_erase_token'))
        batch_op.drop_column('erased_at')
        batch_op.drop_column('erase_feedback')
        batch_op.drop_column('erase_token')

    # ### end Alembic commands ###
