"""Opravený foreign key s názvom pre mesto_id

Revision ID: 77fe8d51e432
Revises: f8798e999ff3
Create Date: 2025-08-05 13:24:17.786006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe8d51e432'
down_revision = 'f8798e999ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inzerat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inzerat_mesto', 'mesto', ['mesto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inzerat', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inzerat_mesto', type_='foreignkey')
        batch_op.drop_column('mesto_id')

    # ### end Alembic commands ###
