"""user settings fields (theme, privacy, follow, soft-delete)

Revision ID: 7e3f316b3cb9
Revises: f3648ce98e01
Create Date: 2025-09-23 14:28:30.603866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3f316b3cb9'
down_revision = 'f3648ce98e01'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(20), nullable=False, server_default='system'))

        batch_op.add_column(sa.Column('verejny_ucet', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('zverejnovat_videa', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('povolit_hodnotenie', sa.Boolean(), nullable=False, server_default=sa.text('1')))

        batch_op.add_column(sa.Column('follow_mode', sa.String(16), nullable=False, server_default='all'))
        batch_op.add_column(sa.Column('follow_zanre', sa.String(255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('follow_entities', sa.String(255), nullable=False, server_default=''))

        batch_op.add_column(sa.Column('erase_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('erase_deadline_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ak ti autogenerate pridal index mimo batch bloku, ten kľudne nechaj:
    # op.create_index('ix_user_visible', 'pouzivatel', ['aktivny','is_deleted','verejny_ucet'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.drop_index('ix_user_visible')
        batch_op.drop_index(batch_op.f('ix_pouzivatel_moderator_podrola'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('erase_deadline_at')
        batch_op.drop_column('erase_requested_at')
        batch_op.drop_column('follow_entities')
        batch_op.drop_column('follow_zanre')
        batch_op.drop_column('follow_mode')
        batch_op.drop_column('povolit_hodnotenie')
        batch_op.drop_column('zverejnovat_videa')
        batch_op.drop_column('verejny_ucet')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
