"""ratings: note field

Revision ID: 8432539efe77
Revises: 84e64a5fc80f
Create Date: 2025-09-26 14:31:23.112627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8432539efe77'
down_revision = '84e64a5fc80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))
        batch_op.alter_column('stars',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rating', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.drop_column('note')

    # ### end Alembic commands ###
