"""add Reklama

Revision ID: 8d7c48758b48
Revises: af2ab28a8bfc
Create Date: 2025-09-10 16:06:08.265201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7c48758b48'
down_revision = 'af2ab28a8bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reklama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=False),
    sa.Column('nazov', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('foto_nazov', sa.String(length=255), nullable=True),
    sa.Column('start_dt', sa.DateTime(), nullable=False),
    sa.Column('end_dt', sa.DateTime(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reklama', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reklama_pouzivatel_id'), ['pouzivatel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reklama', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reklama_pouzivatel_id'))

    op.drop_table('reklama')
    # ### end Alembic commands ###
