"""account deletion: token, feedback, erased_at

Revision ID: 93c7beb658e0
Revises: 779b1c680b82
Create Date: 2025-09-24 12:15:46.050925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c7beb658e0'
down_revision = '779b1c680b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pouzivatel_moderator_podrola'), ['moderator_podrola'], unique=False)
        batch_op.create_index('ix_user_visible', ['aktivny', 'is_deleted', 'verejny_ucet'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.drop_index('ix_user_visible')
        batch_op.drop_index(batch_op.f('ix_pouzivatel_moderator_podrola'))

    # ### end Alembic commands ###
