"""Inicializácia čistej databázy

Revision ID: 949d968ce0fb
Revises: 4708198eb159
Create Date: 2025-07-21 12:28:09.956651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949d968ce0fb'
down_revision = '4708198eb159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pouzivatel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prezyvka', sa.String(length=50), nullable=False),
    sa.Column('meno', sa.String(length=100), nullable=True),
    sa.Column('priezvisko', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('heslo', sa.String(length=200), nullable=False),
    sa.Column('instrument', sa.String(length=100), nullable=True),
    sa.Column('doplnkovy_nastroj', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('obec', sa.String(length=100), nullable=True),
    sa.Column('datum_registracie', sa.DateTime(), nullable=True),
    sa.Column('aktivny', sa.Boolean(), nullable=True),
    sa.Column('profil_fotka', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('prezyvka')
    )
    op.create_table('dopyt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meno', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('typ_akcie', sa.String(length=100), nullable=True),
    sa.Column('miesto', sa.String(length=100), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('cas_od', sa.Time(), nullable=True),
    sa.Column('cas_do', sa.Time(), nullable=True),
    sa.Column('popis', sa.Text(), nullable=True),
    sa.Column('rozpocet', sa.Float(), nullable=True),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galeria_pouzivatel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazov_suboru', sa.String(length=200), nullable=False),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inzerat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=True),
    sa.Column('kategoria', sa.String(length=50), nullable=True),
    sa.Column('mesto', sa.String(length=100), nullable=True),
    sa.Column('doprava', sa.String(length=50), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('popis', sa.Text(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skupina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazov', sa.String(length=100), nullable=False),
    sa.Column('zaner', sa.String(length=100), nullable=True),
    sa.Column('mesto', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.Column('popis', sa.Text(), nullable=True),
    sa.Column('profil_fotka_skupina', sa.String(length=120), nullable=True),
    sa.Column('datum_vytvorenia', sa.DateTime(), nullable=True),
    sa.Column('zakladatel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zakladatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_pouzivatel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=255), nullable=False),
    sa.Column('popis', sa.String(length=255), nullable=True),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galeria_skupina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazov_suboru', sa.String(length=200), nullable=False),
    sa.Column('skupina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skupina_id'], ['skupina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skupina_clenovia',
    sa.Column('skupina_id', sa.Integer(), nullable=True),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.ForeignKeyConstraint(['skupina_id'], ['skupina.id'], )
    )
    op.create_table('udalost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazov', sa.String(length=100), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('cas_od', sa.Time(), nullable=True),
    sa.Column('cas_do', sa.Time(), nullable=True),
    sa.Column('miesto', sa.String(length=150), nullable=True),
    sa.Column('poznamka', sa.Text(), nullable=True),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=True),
    sa.Column('skupina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.ForeignKeyConstraint(['skupina_id'], ['skupina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_skupina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=300), nullable=False),
    sa.Column('popis', sa.String(length=200), nullable=True),
    sa.Column('skupina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skupina_id'], ['skupina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_skupina')
    op.drop_table('udalost')
    op.drop_table('skupina_clenovia')
    op.drop_table('galeria_skupina')
    op.drop_table('video_pouzivatel')
    op.drop_table('skupina')
    op.drop_table('inzerat')
    op.drop_table('galeria_pouzivatel')
    op.drop_table('dopyt')
    op.drop_table('pouzivatel')
    # ### end Alembic commands ###
