"""ad reports

Revision ID: 95bed036fc9d
Revises: 8d7c48758b48
Create Date: 2025-09-12 09:45:27.556453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bed036fc9d'
down_revision = '8d7c48758b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reklama_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reklama_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['pouzivatel.id'], ),
    sa.ForeignKeyConstraint(['reklama_id'], ['reklama.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['pouzivatel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reklama_report')
    # ### end Alembic commands ###
