"""baseline sync after manual columns

Revision ID: a2b592fdc17b
Revises: f947dd687bc9
Create Date: 2025-09-10 11:51:19.050516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b592fdc17b'
down_revision = 'f947dd687bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.alter_column('account_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'individual'"))
        batch_op.alter_column('searchable',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('skupina_pozvanka', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('stav',
               existing_type=sa.VARCHAR(length=12),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skupina_pozvanka', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('stav',
               existing_type=sa.VARCHAR(length=12),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.alter_column('searchable',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('account_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'individual'"))
        batch_op.alter_column('plan',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))

    # ### end Alembic commands ###
