"""add Podujatie model

Revision ID: af2ab28a8bfc
Revises: e641ee96ccd5
Create Date: 2025-09-10 14:54:00.419184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2ab28a8bfc'
down_revision = 'e641ee96ccd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podujatie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pouzivatel_id', sa.Integer(), nullable=False),
    sa.Column('nazov', sa.String(length=120), nullable=False),
    sa.Column('organizator', sa.String(length=120), nullable=True),
    sa.Column('miesto', sa.String(length=120), nullable=True),
    sa.Column('start_dt', sa.DateTime(), nullable=False),
    sa.Column('popis', sa.Text(), nullable=True),
    sa.Column('foto_nazov', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pouzivatel_id'], ['pouzivatel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podujatie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podujatie_pouzivatel_id'), ['pouzivatel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podujatie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podujatie_pouzivatel_id'))

    op.drop_table('podujatie')
    # ### end Alembic commands ###
