"""dopyt: add cta_sent_at

Revision ID: b149d2c7430c
Revises: 8432539efe77
Create Date: 2025-09-29 13:21:07.762819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b149d2c7430c'
down_revision = '8432539efe77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.drop_column('cta_sent_at')

    # ### end Alembic commands ###
