"""skupina: add typ (hudobna/tanecna)

Revision ID: b22712aac778
Revises: 0cd5534fc533
Create Date: 2025-10-11 14:16:04.691736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22712aac778'
down_revision = '0cd5534fc533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skupina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typ', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_skupina_typ'), ['typ'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skupina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skupina_typ'))
        batch_op.drop_column('typ')

    # ### end Alembic commands ###
