"""spravy: soft delete flags

Revision ID: d4fe0b0a1870
Revises: 188b7f45e688
Create Date: 2025-08-22 09:46:34.585587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fe0b0a1870'
down_revision = '188b7f45e688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spravy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_recipient', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spravy', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_recipient')
        batch_op.drop_column('deleted_by_sender')

    # ### end Alembic commands ###
