"""Pridany popis do Udalost

Revision ID: e66d91c52797
Revises: 949d968ce0fb
Create Date: 2025-07-21 22:35:29.008097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66d91c52797'
down_revision = '949d968ce0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('udalost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('udalost', schema=None) as batch_op:
        batch_op.drop_column('popis')

    # ### end Alembic commands ###
