"""Allow NULL in dopyt.pouzivatel_id

Revision ID: eb7190782479
Revises: 326c001caaa5
Create Date: 2025-08-18 15:22:59.919306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7190782479'
down_revision = '326c001caaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.alter_column('pouzivatel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dopyt', schema=None) as batch_op:
        batch_op.alter_column('pouzivatel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
