"""registracia: FO/ICO polia + indexy (servis)

Revision ID: f3648ce98e01
Revises: 95bed036fc9d
Create Date: 2025-09-16 12:12:32.720181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3648ce98e01'
down_revision = '95bed036fc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rola', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('hud_oblast', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('hud_spec', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tanec_spec', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tanec_ine', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ucitel_predmety', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ucitel_ine', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('org_zaradenie', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('org_zaradenie_ine', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('dic', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ic_dph', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sidlo_ulica', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sidlo_psc', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sidlo_mesto', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_pouzivatel_hud_oblast'), ['hud_oblast'], unique=False)
        batch_op.create_index(batch_op.f('ix_pouzivatel_org_zaradenie'), ['org_zaradenie'], unique=False)
        batch_op.create_index(batch_op.f('ix_pouzivatel_rola'), ['rola'], unique=False)
        batch_op.create_index(batch_op.f('ix_pouzivatel_sidlo_mesto'), ['sidlo_mesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_pouzivatel_sidlo_psc'), ['sidlo_psc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pouzivatel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pouzivatel_sidlo_psc'))
        batch_op.drop_index(batch_op.f('ix_pouzivatel_sidlo_mesto'))
        batch_op.drop_index(batch_op.f('ix_pouzivatel_rola'))
        batch_op.drop_index(batch_op.f('ix_pouzivatel_org_zaradenie'))
        batch_op.drop_index(batch_op.f('ix_pouzivatel_hud_oblast'))
        batch_op.drop_column('sidlo_mesto')
        batch_op.drop_column('sidlo_psc')
        batch_op.drop_column('sidlo_ulica')
        batch_op.drop_column('ic_dph')
        batch_op.drop_column('dic')
        batch_op.drop_column('org_zaradenie_ine')
        batch_op.drop_column('org_zaradenie')
        batch_op.drop_column('ucitel_ine')
        batch_op.drop_column('ucitel_predmety')
        batch_op.drop_column('tanec_ine')
        batch_op.drop_column('tanec_spec')
        batch_op.drop_column('hud_spec')
        batch_op.drop_column('hud_oblast')
        batch_op.drop_column('rola')

    # ### end Alembic commands ###
