"""Pridaný stĺpec celodenne k udalostiam

Revision ID: f8798e999ff3
Revises: e66d91c52797
Create Date: 2025-07-21 23:21:52.030006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8798e999ff3'
down_revision = 'e66d91c52797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('udalost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celodenne', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('udalost', schema=None) as batch_op:
        batch_op.drop_column('celodenne')

    # ### end Alembic commands ###
